import os

from groq import Groq
from .memory import ProposalMemory


class ProposalAgent:

    def __init__(self):
        self.memory = ProposalMemory()

        self.llm = Groq(
            api_key=os.environ["GROQ_API_KEY"]
        )

        self.model = "openai/gpt-oss-20b"

    def analyze_rfp(self, rfp_text):
        """Retrieve relevant previous proposal experience."""

        results = self.memory.recall(
            query=rfp_text
        )

        memories = []

        for result in results.results:
            memories.append(result.text)

        return memories

    def retrieve_memories(self, memory_queries):
        """
        Retrieve relevant historical memories using
        targeted queries generated by Member 1.
        """

        memories = []

        for query in memory_queries:

            results = self.memory.recall(
                query=query
            )

            for result in results.results:
                memories.append(result.text)

        # Remove duplicate memories while preserving order
        unique_memories = list(dict.fromkeys(memories))

        return unique_memories

    def generate_recommendations(self, rfp_text):
        """Generate proposal recommendations using RFP + previous experience."""

        memories = self.analyze_rfp(rfp_text)

        memory_context = "\n".join(
            f"- {memory}" for memory in memories
        )

        prompt = f"""
You are a Proposal and RFP Assistant.

Analyze the following RFP and provide practical proposal recommendations.

NEW RFP:
{rfp_text}

RELEVANT PREVIOUS EXPERIENCE:
{memory_context}

Based on the RFP and previous experience:

1. Identify important proposal requirements.
2. Identify lessons from previous experience that should be applied.
3. Identify risks or mistakes to avoid.
4. Suggest specific actions for the proposal team.

Do not invent facts that are not present in the RFP or previous experience.
"""

        response = self.llm.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.2,
        )

        return response.choices[0].message.content

    def generate_integrated_recommendations(
        self,
        rfp_text,
        rfp_analysis,
        memory_queries
    ):
        """
        Generate recommendations using:
        Member 1 RFP analysis
        Member 1 targeted memory queries
        Hindsight historical memories
        """

        memories = self.retrieve_memories(
            memory_queries
        )

        memory_context = "\n".join(
            f"- {memory}" for memory in memories
        )

        prompt = f"""
You are a Proposal and RFP Assistant.

Analyze the current RFP using:

1. The current RFP
2. The RFP analysis
3. Retrieved historical memories

CURRENT RFP:
{rfp_text}

RFP ANALYSIS:
{rfp_analysis}

RETRIEVED HISTORICAL MEMORIES:
{memory_context}

Provide:

1. Important proposal requirements
2. Relevant lessons from previous experience
3. Risks or mistakes to avoid
4. Specific actions for the proposal team

Grounding rules:

- Treat the CURRENT RFP as the source of truth for current requirements.
- Treat RETRIEVED HISTORICAL MEMORIES as the source of truth for previous experience.
- Do not invent facts, numbers, percentages, timelines, tools, costs,
  performance targets, outcomes, or client requirements.
- Do not introduce specific implementation durations unless they are
  explicitly supported by the RFP or retrieved historical memories.
- Do not introduce specific technologies or tools unless they are
  explicitly supported by the RFP or retrieved historical memories.
- If information is missing, say "Not specified" or "Needs to be determined".
- Recommendations may be generated from the available facts, but clearly
  label them as recommendations rather than facts.

Clearly distinguish:
- Current RFP facts
- Historical experience
- Recommendations
"""

        response = self.llm.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.2,
        )

        return {
            "recommendations": response.choices[0].message.content,
            "memories": memories,
            "memory_count": len(memories)
        }


if __name__ == "__main__":

    agent = ProposalAgent()

    rfp_file = "data/rfps/abc_cloud_migration.txt"

    with open(rfp_file, "r", encoding="utf-8") as file:
        rfp = file.read()

    print("\n=== RFP LOADED ===\n")
    print(rfp)

    print("\n=== PROPOSAL RECOMMENDATIONS ===\n")

    recommendations = agent.generate_recommendations(rfp)

    print(recommendations)